---

- name: Play book to build the docker image and push it to the dockerhub
  hosts: ansible-server
  tasks:
   - name: Build the Docker image
     command: docker build -t chandradc/mytomcat:1 .
   - name: Push the image to docker hub
     command: docker push chandradc/mytomcat:1
